services:
    file_api_image.convert_image_worker:
        class: FileApi\WorkerBundle\Workers\ConvertImageWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_image.convert_gif_to_video_worker:
        class: FileApi\WorkerBundle\Workers\ConvertGifToVideoWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_image.reduce_image_file_size_worker:
        class: FileApi\WorkerBundle\Workers\ReduceImageFileSizeWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_image.resize_image_dimensions_worker:
        class: FileApi\WorkerBundle\Workers\ResizeImageDimensionsWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_worker.convert_video_worker:
        class: FileApi\WorkerBundle\Workers\ConvertVideoWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%
