services:
    file_api_image.convert_image_worker:
        class: FileApi\WorkerBundle\Workers\ConvertImageWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.convert_image_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_worker.watermark_image_worker:
        class: FileApi\WorkerBundle\Workers\WatermarkImageWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.watermark_image_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_image.convert_gif_to_video_worker:
        class: FileApi\WorkerBundle\Workers\ConvertGifToVideoWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.convert_gif_to_video_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_image.reduce_image_file_size_worker:
        class: FileApi\WorkerBundle\Workers\ReduceImageFileSizeWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.reduce_image_file_size_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_image.resize_image_dimensions_worker:
        class: FileApi\WorkerBundle\Workers\ResizeImageDimensionsWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.resize_image_dimensions_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_worker.convert_video_worker:
        class: FileApi\WorkerBundle\Workers\ConvertVideoWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.convert_video_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_worker.convert_ttf_font_worker:
        class: FileApi\WorkerBundle\Workers\ConvertTtfFontWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.convert_ttf_font_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_worker.virus_scan_worker:
        class: FileApi\WorkerBundle\Workers\VirusScanWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.virus_scan_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_worker.screenshot_web_page_worker:
        class: FileApi\WorkerBundle\Workers\ScreenshotWebPageWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.screenshot_web_page_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_worker.pgn_parser_worker:
        class: FileApi\WorkerBundle\Workers\PgnParserWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.pgn_parser_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_worker.detect_porn_worker:
        class: FileApi\WorkerBundle\Workers\DetectPornWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.detect_porn_worker
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    file_api_worker.website_mistakes_service:
        class: FileApi\WorkerBundle\Workers\WebsiteMistakesService
        arguments:
            - @doctrine_mongodb
            - @monolog.logger.website_mistakes_service
