imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options: {}
    default_database: %mongodb_db%
    default_commit_options: ~
    document_managers:
        default:
            auto_mapping: true

liip_doctrine_cache:
    namespaces:
        gearman:
            type: file_system

services:
    mongo.connection:
        class: MongoDoctrine\MongoDB\Connection
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getConnection
        calls:
            - [initialize, []]
    mongo:
        class: Mongo
        factory_service: mongo.connection
        factory_method: getMongo

partnermarketing_file_system:
    default_file_system: local_storage
    config:
        amazon_s3:
            key: xxxxxxxx
            secret: xxxxxxxx
            bucket: xxxxxxxx
            region: xxxxxxxx
        local_storage:
            path: /home/fileapi/project/file-system
            url: 'http://files.fileapi.dev'
    tmp_dir: /tmp

gearman:
    bundles:
        WorkerBundle:
            name: FileApiWorkerBundle
            active: true
            include:
                - Workers
    servers: %gearman_servers%
