services:
    convert_image.convert_image_worker:
        class: Convert\ImageBundle\Workers\ConvertImageWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    convert_image.convert_gif_to_video_worker:
        class: Convert\ImageBundle\Workers\ConvertGifToVideoWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    convert_image.reduce_image_file_size_worker:
        class: Convert\ImageBundle\Workers\ReduceImageFileSizeWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%

    convert_image.resize_image_dimensions_worker:
        class: Convert\ImageBundle\Workers\ResizeImageDimensionsWorker
        arguments:
            - @doctrine_mongodb
            - @monolog.logger
            - @partnermarketing_file_system.factory
            - %partnermarketing_file_system.tmp_dir%
